### ISSUE TITLE
cannot run a clean migration

### ISSUE THREAD

**Issue by mcgoooo** [alphagov/publishing-api#815]
### what happens
i get the following error when i try and run migrations

```
StandardError: An error has occurred, this and all later migrations canceled:

Table 'live_content_items' has no foreign key for draft_content_item
/Users/andrewhilton/Code/publishing-api/db/migrate/20151124113325_allow_null_draft_content_id.rb:3:in `change'
/Users/andrewhilton/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/andrewhilton/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
ArgumentError: Table 'live_content_items' has no foreign key for draft_content_item
/Users/andrewhilton/Code/publishing-api/db/migrate/20151124113325_allow_null_draft_content_id.rb:3:in `change'
/Users/andrewhilton/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/andrewhilton/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### what do you expect to happen
migrations run cleanly

### steps to reproduce
```
rake db:create
rake db:migrate
```

**Comment by kevindew** [comment]
Hello @mcgoooo 👋 

So as discussed on slack, you'd be better off with [`rake db:setup`](http://edgeguides.rubyonrails.org/active_record_migrations.html#setup-the-database) as it saves you having to worry about going through the history of the database to create it.

That said it should have worked for you, and testing it locally I haven't hit the same failure point you have. I hit a much later one and I've just put together a [PR](https://github.com/alphagov/publishing-api/pull/819) to fix it. 

my output on that branch is: 
```
➜  publishing-api git:(fix-old-migrations) rake db:drop
Dropped database 'publishing_api_development'
Dropped database 'publishing_api_test'
➜  publishing-api git:(fix-old-migrations) rake db:create
Created database 'publishing_api_development'
Created database 'publishing_api_test'
➜  publishing-api git:(fix-old-migrations) rake db:migrate
== 20150908145609 CreateEvents: migrating =====================================
-- create_table(:events, {})
   -> 0.0170s
== 20150908145609 CreateEvents: migrated (0.0170s) ============================

== 20150922125847 AddDerivedRepresentations: migrating ========================
-- create_table(:draft_content_items, {})
   -> 0.0123s
-- add_index(:draft_content_items, [:content_id, :locale], {:unique=>true})
   -> 0.0039s
-- create_table(:live_content_items, {})
   -> 0.0044s
-- add_index(:live_content_items, [:content_id, :locale], {:unique=>true})
   -> 0.0029s
-- create_table(:link_sets, {})
   -> 0.0037s
-- add_index(:link_sets, :content_id, {:unique=>true})
   -> 0.0025s
== 20150922125847 AddDerivedRepresentations: migrated (0.0299s) ===============

== 20151012094145 SetEmptyDefaultForJsonFields: migrating =====================
-- change_column_default(:events, :payload, {})
   -> 0.0021s
-- change_column_default(:draft_content_items, :access_limited, {})
   -> 0.0015s
-- change_column_default(:draft_content_items, :details, {})
   -> 0.0015s
-- change_column_default(:draft_content_items, :metadata, {})
   -> 0.0015s
-- change_column_default(:draft_content_items, :redirects, [])
   -> 0.0015s
-- change_column_default(:draft_content_items, :routes, [])
   -> 0.0015s
-- change_column_default(:live_content_items, :details, {})
   -> 0.0014s
-- change_column_default(:live_content_items, :metadata, {})
   -> 0.0014s
-- change_column_default(:live_content_items, :redirects, [])
   -> 0.0021s
-- change_column_default(:live_content_items, :routes, [])
   -> 0.0014s
-- change_column_default(:link_sets, :links, {})
   -> 0.0011s
== 20151012094145 SetEmptyDefaultForJsonFields: migrated (0.0175s) ============

== 20151012095129 SetDefaultVersionToZero: migrating ==========================
-- change_column_default(:draft_content_items, :version, 0)
   -> 0.0015s
-- change_column_default(:live_content_items, :version, 0)
   -> 0.0014s
-- change_column_default(:link_sets, :version, 0)
   -> 0.0010s
== 20151012095129 SetDefaultVersionToZero: migrated (0.0039s) =================

== 20151014133602 AddDraftContentItemIdToLiveContentItem: migrating ===========
-- add_reference(:live_content_items, :draft_content_item, {:index=>true})
   -> 0.0093s
-- change_column_null(:live_content_items, :draft_content_item_id, false)
   -> 0.0008s
== 20151014133602 AddDraftContentItemIdToLiveContentItem: migrated (0.0169s) ==

== 20151015102423 CreatePathReservations: migrating ===========================
-- create_table(:path_reservations, {})
   -> 0.0059s
-- add_index(:path_reservations, :base_path, {:unique=>true})
   -> 0.0025s
== 20151015102423 CreatePathReservations: migrated (0.0085s) ==================

== 20151016145941 AddForeignKeyToLinkContentItems: migrating ==================
-- add_foreign_key(:live_content_items, :draft_content_items)
   -> 0.0114s
== 20151016145941 AddForeignKeyToLinkContentItems: migrated (0.0116s) =========

== 20151021091248 CreateVersions: migrating ===================================
-- create_table(:versions, {})
   -> 0.0097s
== 20151021091248 CreateVersions: migrated (0.0098s) ==========================

== 20151026112807 MakeBasePathUnique: migrating ===============================
-- add_index(:draft_content_items, :base_path, {:unique=>true})
   -> 0.0033s
-- add_index(:live_content_items, :base_path, {:unique=>true})
   -> 0.0028s
== 20151026112807 MakeBasePathUnique: migrated (0.0062s) ======================

== 20151029102155 SetDefaultLocaleToEn: migrating =============================
-- change_column_default(:draft_content_items, :locale, "en")
   -> 0.0018s
-- change_column_default(:live_content_items, :locale, "en")
   -> 0.0014s
== 20151029102155 SetDefaultLocaleToEn: migrated (0.0033s) ====================

== 20151029110606 MoveMetadataFieldsToTopLevel: migrating =====================
-- add_column(:draft_content_items, :need_ids, :json, {:default=>[]})
   -> 0.0098s
-- add_column(:draft_content_items, :update_type, :string)
   -> 0.0006s
-- add_column(:draft_content_items, :phase, :string, {:default=>"live"})
   -> 0.0073s
-- add_column(:draft_content_items, :analytics_identifier, :string)
   -> 0.0003s
-- add_column(:live_content_items, :need_ids, :json, {:default=>[]})
   -> 0.0075s
-- add_column(:live_content_items, :update_type, :string)
   -> 0.0003s
-- add_column(:live_content_items, :phase, :string, {:default=>"live"})
   -> 0.0082s
-- add_column(:live_content_items, :analytics_identifier, :string)
   -> 0.0007s
Migrating MoveMetadataFieldsToTopLevel::DraftContentItem data...

Migrating MoveMetadataFieldsToTopLevel::LiveContentItem data...

== 20151029110606 MoveMetadataFieldsToTopLevel: migrated (0.0469s) ============

== 20151029144554 FixNullLinksHashes: migrating ===============================
-- change_column_null(:link_sets, :links, false, {})
   -> 0.0031s
== 20151029144554 FixNullLinksHashes: migrated (0.0032s) ======================

== 20151105154432 RemoveMetadataField: migrating ==============================
-- remove_column(:live_content_items, :metadata)
   -> 0.0004s
-- remove_column(:draft_content_items, :metadata)
   -> 0.0005s
== 20151105154432 RemoveMetadataField: migrated (0.0010s) =====================

== 20151105154759 RemoveVersionFields: migrating ==============================
-- remove_column(:draft_content_items, :version)
   -> 0.0003s
-- remove_column(:live_content_items, :version)
   -> 0.0003s
-- remove_column(:link_sets, :version)
   -> 0.0002s
== 20151105154759 RemoveVersionFields: migrated (0.0009s) =====================

== 20151119100750 ChangeDescriptionColumnTypes: migrating =====================
-- add_column(:draft_content_items, :new_description, :json)
   -> 0.0005s
-- change_column_default(:draft_content_items, :new_description, {:value=>nil})
   -> 0.0018s
-- rename_column(:draft_content_items, :description, :old_description)
   -> 0.0032s
-- rename_column(:draft_content_items, :new_description, :description)
   -> 0.0026s
-- add_column(:live_content_items, :new_description, :json)
   -> 0.0004s
-- change_column_default(:live_content_items, :new_description, {:value=>nil})
   -> 0.0019s
-- rename_column(:live_content_items, :description, :old_description)
   -> 0.0023s
-- rename_column(:live_content_items, :new_description, :description)
   -> 0.0020s
== 20151119100750 ChangeDescriptionColumnTypes: migrated (0.0306s) ============

== 20151124113325 AllowNullDraftContentId: migrating ==========================
-- remove_foreign_key(:live_content_items, :draft_content_items)
   -> 0.0029s
-- change_column_null(:live_content_items, :draft_content_item_id, true)
   -> 0.0002s
== 20151124113325 AllowNullDraftContentId: migrated (0.0032s) =================

== 20151126102119 AddLinksTable: migrating ====================================
-- create_table(:links, {})
   -> 0.0084s
-- add_index(:links, [:link_set_id, :target_content_id])
   -> 0.0028s
== 20151126102119 AddLinksTable: migrated (0.0113s) ===========================

== 20151126135748 RetireLinksColumn: migrating ================================
-- rename_column(:link_sets, :links, :legacy_links)
   -> 0.0018s
== 20151126135748 RetireLinksColumn: migrated (0.0019s) =======================

== 20151215102213 CreateUsers: migrating ======================================
-- create_table(:users, {})
   -> 0.0057s
== 20151215102213 CreateUsers: migrated (0.0058s) =============================

== 20151231125222 ExtractAccessLimiting: migrating ============================
-- create_table(:access_limits, {})
   -> 0.0053s
-- add_index(:access_limits, [:target_type, :target_id], {:name=>"index_access_limits_on_target"})
   -> 0.0025s
== 20151231125222 ExtractAccessLimiting: migrated (0.0100s) ===================

== 20160101090938 AddTimestampsToLinkSet: migrating ===========================
-- add_timestamps(:link_sets, {:null=>true})
   -> 0.0007s
== 20160101090938 AddTimestampsToLinkSet: migrated (0.0008s) ==================

== 20160101090939 NewObjectModel: migrating ===================================
-- create_table(:locations, {})
   -> 0.0061s
-- change_column_null(:locations, :content_item_id, false)
   -> 0.0006s
-- add_index(:locations, [:content_item_id, :base_path])
   -> 0.0021s
-- create_table(:translations, {})
   -> 0.0039s
-- change_column_null(:translations, :content_item_id, false)
   -> 0.0006s
-- add_index(:translations, [:content_item_id, :locale])
   -> 0.0019s
-- create_table(:states, {})
   -> 0.0040s
-- change_column_null(:states, :content_item_id, false)
   -> 0.0005s
-- add_index(:states, [:content_item_id, :name])
   -> 0.0024s
-- create_table(:user_facing_versions, {})
   -> 0.0035s
-- change_column_null(:user_facing_versions, :content_item_id, false)
   -> 0.0009s
-- add_index(:user_facing_versions, [:content_item_id, :number])
   -> 0.0031s
-- create_table("lock_versions", {})
   -> 0.0058s
-- create_table(:content_items, {})
   -> 0.0067s
-- add_column(:access_limits, :content_item_id, :integer)
   -> 0.0004s
-- change_column_null(:access_limits, :target_id, true)
   -> 0.0003s
-- change_column_null(:access_limits, :target_type, true)
   -> 0.0002s
-- Copying content items
   -> 0.0010s
LiveContentItems: 0
DraftContentItems: 0
ContentItems: 0
-- Creating states
   -> 0.0004s
States: 0, Content Items: 0
-- Creating translations
   -> 0.0005s
Translations: 0, Content Items: 0
-- Creating locations
   -> 0.0005s
Locations: 0, Content Items: 0
-- Creating lock versions for content items
   -> 0.0017s
LockVersions: 0, Content Items: 0
-- Creating lock versions for link sets
   -> 0.0007s
LockVersions: 0, Link Sets: 0
-- Updating access limits
   -> 0.0025s
AccessLimit: 0
-- Creating user facing versions for live items
   -> 0.0004s
UserFacingVersion: 0
-- Creating user facing versions for draft items
   -> 0.0005s
UserFacingVersion: 0
== 20160101090939 NewObjectModel: migrated (0.0941s) ==========================

== 20160111093455 FixNilDescriptions: migrating ===============================
== 20160111093455 FixNilDescriptions: migrated (0.0037s) ======================

== 20160111103706 RemoveAccessLimitedColumn: migrating ========================
-- remove_column(:draft_content_items, :access_limited, :json, {:default=>{}})
   -> 0.0004s
== 20160111103706 RemoveAccessLimitedColumn: migrated (0.0005s) ===============

== 20160115162121 AddIndexesForContentCollectionAccess: migrating =============
-- add_index(:draft_content_items, :format)
   -> 0.0032s
-- add_index(:live_content_items, :format)
   -> 0.0025s
-- add_index(:versions, :target_id)
   -> 0.0024s
== 20160115162121 AddIndexesForContentCollectionAccess: migrated (0.0083s) ====

== 20160125143518 AddPassthroughFieldToLink: migrating ========================
-- add_column(:links, :passthrough_hash, :json)
   -> 0.0005s
-- change_column_null(:links, :target_content_id, true)
   -> 0.0003s
== 20160125143518 AddPassthroughFieldToLink: migrated (0.0008s) ===============

== 20160203142246 RenamePutLinksToPatchLinks: migrating =======================
== 20160203142246 RenamePutLinksToPatchLinks: migrated (0.0056s) ==============

== 20160209143547 AddDocumentTypeAndSchemaNameToContentItems: migrating =======
-- add_column(:content_items, :document_type, :string)
   -> 0.0004s
-- add_column(:content_items, :schema_name, :string)
   -> 0.0002s
== 20160209143547 AddDocumentTypeAndSchemaNameToContentItems: migrated (0.0008s)

== 20160224104428 AddIndexesToImprovePerformance: migrating ===================
-- add_index(:content_items, :content_id)
   -> 0.0025s
-- add_index(:content_items, :format)
   -> 0.0024s
-- add_index(:content_items, :publishing_app)
   -> 0.0023s
-- add_index(:content_items, :rendering_app)
   -> 0.0025s
-- add_index(:links, :link_type)
   -> 0.0026s
-- add_index(:lock_versions, [:target_id, :target_type])
   -> 0.0030s
-- add_index(:locations, :base_path)
   -> 0.0027s
== 20160224104428 AddIndexesToImprovePerformance: migrated (0.0183s) ==========

== 20160225113309 CreateContentStorePayloadVersions: migrating ================
-- create_table(:content_store_payload_versions, {})
   -> 0.0041s
-- add_index(:content_store_payload_versions, :content_item_id, {:unique=>true})
   -> 0.0029s
== 20160225113309 CreateContentStorePayloadVersions: migrated (0.0071s) =======

== 20160303101053 DropContentStorePayloadVersions: migrating ==================
-- drop_table(:content_store_payload_versions)
   -> 0.0006s
== 20160303101053 DropContentStorePayloadVersions: migrated (0.0007s) =========

== 20160307112043 IndexContentItemsPublicUpdatedAt: migrating =================
-- add_index(:content_items, :public_updated_at)
   -> 0.0033s
== 20160307112043 IndexContentItemsPublicUpdatedAt: migrated (0.0034s) ========

== 20160309155913 DropOldTables: migrating ====================================
-- drop_table(:draft_content_items)
   -> 0.0012s
-- drop_table(:live_content_items)
   -> 0.0011s
-- drop_table(:versions)
   -> 0.0011s
-- remove_column(:content_items, :draft_content_item_id)
   -> 0.0003s
-- remove_column(:content_items, :live_content_item_id)
   -> 0.0002s
-- remove_column(:content_items, :access_limited)
   -> 0.0004s
-- remove_column(:access_limits, :target_id)
   -> 0.0005s
-- remove_column(:access_limits, :target_type)
   -> 0.0003s
== 20160309155913 DropOldTables: migrated (0.0053s) ===========================

== 20160315070023 AddContentItemsIndexOnDocumentType: migrating ===============
-- add_index(:content_items, :document_type)
   -> 0.0033s
== 20160315070023 AddContentItemsIndexOnDocumentType: migrated (0.0033s) ======

== 20160315123002 AddIndexToLinksTarget: migrating ============================
-- add_index(:links, :target_content_id)
   -> 0.0025s
-- add_index(:links, [:target_content_id, :link_type])
   -> 0.0023s
== 20160315123002 AddIndexToLinksTarget: migrated (0.0049s) ===================

== 20160418144039 AddRequestIdToEvents: migrating =============================
-- add_column(:events, :request_id, :string)
   -> 0.0004s
== 20160418144039 AddRequestIdToEvents: migrated (0.0004s) ====================

== 20160420093816 AddContentIdToEvent: migrating ==============================
-- add_column(:events, :content_id, :string)
   -> 0.0003s
-- add_index(:events, :content_id)
   -> 0.0026s
== 20160420093816 AddContentIdToEvent: migrated (0.0035s) =====================

== 20160429095656 ChangeWithdrawnToUnpublished: migrating =====================
-- create_table(:unpublishings, {})
   -> 0.0052s
-- add_index(:unpublishings, :content_item_id)
   -> 0.0028s
-- add_index(:unpublishings, [:content_item_id, :type])
   -> 0.0033s
== 20160429095656 ChangeWithdrawnToUnpublished: migrated (0.0115s) ============

== 20160429123756 AddFirstPublishedAt: migrating ==============================
-- add_column(:content_items, :first_published_at, :datetime)
   -> 0.0008s
== 20160429123756 AddFirstPublishedAt: migrated (0.0009s) =====================

== 20160505133601 RenameAlternativeUrl: migrating =============================
-- rename_column(:unpublishings, :alternative_url, :alternative_path)
   -> 0.0021s
== 20160505133601 RenameAlternativeUrl: migrated (0.0022s) ====================

== 20160512122441 IndexContentItemsOnUpdatedAt: migrating =====================
-- add_index(:content_items, :updated_at)
   -> 0.0025s
== 20160512122441 IndexContentItemsOnUpdatedAt: migrated (0.0025s) ============

== 20160513163056 DeduplicateLinks: migrating =================================
0 unique records of  total duplicated
0 records deleted
== 20160513163056 DeduplicateLinks: migrated (0.0113s) ========================

== 20160516135536 RemoveColumnLegacyLinksFromLinkSet: migrating ===============
-- remove_column(:link_sets, :legacy_links, :json)
   -> 0.0005s
== 20160516135536 RemoveColumnLegacyLinksFromLinkSet: migrated (0.0006s) ======

== 20160517134907 CreateLinkables: migrating ==================================
-- create_table(:linkables, {})
   -> 0.0056s
-- add_index(:linkables, :document_type)
   -> 0.0031s
== 20160517134907 CreateLinkables: migrated (0.0088s) =========================

== 20160524210649 CreateIndexOnLinkablesBasePath: migrating ===================
-- add_index(:linkables, :base_path)
   -> 0.0031s
== 20160524210649 CreateIndexOnLinkablesBasePath: migrated (0.0032s) ==========

== 20160607153243 RemoveFormatFromContentItem: migrating ======================
-- remove_column(:content_items, :format, :string)
   -> 0.0004s
== 20160607153243 RemoveFormatFromContentItem: migrated (0.0005s) =============

== 20160614144815 AddLastEditedAtToContentItem: migrating =====================
-- add_column(:content_items, :last_edited_at, :datetime)
   -> 0.0004s
-- add_index(:content_items, :last_edited_at)
   -> 0.0035s
== 20160614144815 AddLastEditedAtToContentItem: migrated (0.0041s) ============

== 20160715153009 AddContentItemIndexes: migrating ============================
-- add_index(:access_limits, :content_item_id)
   -> 0.0029s
-- add_index(:linkables, :content_item_id)
   -> 0.0024s
-- add_index(:states, :content_item_id)
   -> 0.0024s
-- add_index(:translations, :content_item_id)
   -> 0.0025s
== 20160715153009 AddContentItemIndexes: migrated (0.0105s) ===================

== 20160729091936 RenameAlphaTaxonLinkType: migrating =========================
== 20160729091936 RenameAlphaTaxonLinkType: migrated (0.0018s) ================

== 20160816141116 RemovePathReservationForFindLocalCouncil: migrating =========
== 20160816141116 RemovePathReservationForFindLocalCouncil: migrated (0.0078s)

== 20160912141753 DropPassthroughHashFromLinks: migrating =====================
-- remove_column(:links, :passthrough_hash, :json)
   -> 0.0003s
== 20160912141753 DropPassthroughHashFromLinks: migrated (0.0010s) ============

== 20161003145646 AddPositionToLinks: migrating ===============================
-- add_column(:links, :position, :integer)
   -> 0.0005s
== 20161003145646 AddPositionToLinks: migrated (0.0005s) ======================

== 20161006115515 AddPositionToExistingLinks: migrating =======================
== 20161006115515 AddPositionToExistingLinks: migrated (0.0028s) ==============

== 20161006115850 MakePositionRequired: migrating =============================
-- change_column(:links, :position, :integer, {:null=>false, :default=>0})
   -> 0.0040s
== 20161006115850 MakePositionRequired: migrated (0.0041s) ====================

== 20161007080213 CreateChangeNotes: migrating ================================
-- create_table(:change_notes, {})
   -> 0.0094s
== 20161007080213 CreateChangeNotes: migrated (0.0094s) =======================

== 20161013104311 RemoveLinkables: migrating ==================================
-- drop_table(:linkables)
   -> 0.0008s
== 20161013104311 RemoveLinkables: migrated (0.0008s) =========================

== 20161021161826 MakeEventPayloadNullable: migrating =========================
-- change_column_null(:events, :payload, true)
   -> 0.0003s
== 20161021161826 MakeEventPayloadNullable: migrated (0.0004s) ================

== 20161027165922 AddUnpublishedAt: migrating =================================
-- add_column(:unpublishings, :unpublished_at, :datetime, {:null=>true})
   -> 0.0005s
== 20161027165922 AddUnpublishedAt: migrated (0.0006s) ========================

== 20161102115422 CreateActions: migrating ====================================
-- create_table(:actions)
   -> 0.0120s
== 20161102115422 CreateActions: migrated (0.0121s) ===========================

== 20161104181821 UpdateChangeNotes: migrating ================================
-- change_table(:change_notes)
   -> 0.0046s
== 20161104181821 UpdateChangeNotes: migrated (0.0047s) =======================

== 20161209134135 MergePillarTableColumns: migrating ==========================
-- add_column(:content_items, :state, :string)
   -> 0.0005s
-- add_column(:content_items, :locale, :string)
   -> 0.0003s
-- add_column(:content_items, :user_facing_version, :integer)
   -> 0.0004s
-- add_column(:content_items, :base_path, :string)
   -> 0.0003s
== 20161209134135 MergePillarTableColumns: migrated (0.0017s) =================

== 20161209135851 PopulatePillarTableData: migrating ==========================
-- execute("UPDATE content_items SET state = (\n              SELECT states.name FROM states\n              WHERE states.content_item_id = content_items.id\n            )")
   -> 0.0069s
-- execute("UPDATE content_items SET locale = (\n              SELECT translations.locale FROM translations\n              WHERE translations.content_item_id = content_items.id\n            )")
   -> 0.0019s
-- execute("UPDATE content_items SET user_facing_version = (\n              SELECT user_facing_versions.number FROM user_facing_versions\n              WHERE user_facing_versions.content_item_id = content_items.id\n            )")
   -> 0.0015s
-- execute("UPDATE content_items SET base_path = (\n              SELECT locations.base_path FROM locations\n              WHERE locations.content_item_id = content_items.id\n            )")
   -> 0.0019s
== 20161209135851 PopulatePillarTableData: migrated (0.0125s) =================

== 20161214113229 PillarColumnDefaults: migrating =============================
-- change_column(:content_items, :state, :string, {:null=>false})
   -> 0.0008s
-- change_column(:content_items, :locale, :string, {:null=>false})
   -> 0.0008s
-- change_column(:content_items, :user_facing_version, :integer, {:null=>false, :default=>1})
   -> 0.0049s
== 20161214113229 PillarColumnDefaults: migrated (0.0067s) ====================

== 20161219102828 AddIndexesToContentItem: migrating ==========================
-- add_index(:content_items, [:content_id, :state, :locale], {:algorithm=>:concurrently})
   -> 0.0048s
-- add_index(:content_items, [:state, :base_path], {:algorithm=>:concurrently})
   -> 0.0042s
== 20161219102828 AddIndexesToContentItem: migrated (0.0091s) =================

== 20161219143746 AddContentStoreToContentItems: migrating ====================
-- add_column(:content_items, :content_store, :string)
   -> 0.0005s
== 20161219143746 AddContentStoreToContentItems: migrated (0.0005s) ===========

== 20161220090001 MakeContentIdUuidType: migrating ============================
-- change_column(:content_items, :content_id, "UUID USING content_id::uuid")
   -> 0.0187s
-- change_column(:events, :content_id, "UUID USING content_id::uuid")
   -> 0.0063s
-- change_column(:link_sets, :content_id, "UUID USING content_id::uuid")
   -> 0.0039s
-- change_column(:links, :target_content_id, "UUID USING target_content_id::uuid")
   -> 0.0113s
== 20161220090001 MakeContentIdUuidType: migrated (0.0405s) ===================

== 20161220134413 CreateDocuments: migrating ==================================
-- create_table(:documents)
   -> 0.0060s
-- add_index(:documents, [:content_id, :locale], {:unique=>true})
   -> 0.0030s
== 20161220134413 CreateDocuments: migrated (0.0091s) =========================

== 20161220161528 PopulateContentStoreField: migrating ========================
-- execute("UPDATE content_items SET content_store = (\n              SELECT\n              CASE\n                WHEN state = 'draft' THEN 'draft'\n                WHEN state IN ('published', 'unpublished')\n                AND (unpublishings.type IS NULL OR unpublishings.type != 'substitute') THEN 'live'\n                ELSE NULL\n              END\n              FROM content_items c\n              LEFT JOIN\n                unpublishings ON state = 'unpublished'\n                AND\n                unpublishings.content_item_id = c.id\n              WHERE c.id = content_items.id\n             )")
   -> 0.0079s
== 20161220161528 PopulateContentStoreField: migrated (0.0080s) ===============

== 20170105104520 AddLockVersionToLinkSet: migrating ==========================
-- add_column(:link_sets, :lock_version, :integer)
   -> 0.0009s
-- change_column(:link_sets, :lock_version, :integer, {:default=>1})
   -> 0.0023s
== 20170105104520 AddLockVersionToLinkSet: migrated (0.0033s) =================

== 20170106113000 UniqueUserFacingVersionForContentIdAndLocale: migrating =====
-- add_index(:content_items, [:content_id, :locale, :user_facing_version], {:unique=>true, :algorithm=>:concurrently, :name=>"index_unique_ufv_content_id_locale"})
   -> 0.0037s
== 20170106113000 UniqueUserFacingVersionForContentIdAndLocale: migrated (0.0038s)

== 20170106113100 UniqueContentStoreForContentIdAndLocale: migrating ==========
-- add_index(:content_items, [:content_id, :locale, :content_store], {:unique=>true, :algorithm=>:concurrently})
   -> 0.0036s
== 20170106113100 UniqueContentStoreForContentIdAndLocale: migrated (0.0037s) =

== 20170106113200 UniqueContentStoreForBasePath: migrating ====================
-- add_index(:content_items, [:base_path, :content_store], {:unique=>true, :algorithm=>:concurrently})
   -> 0.0042s
== 20170106113200 UniqueContentStoreForBasePath: migrated (0.0042s) ===========

== 20170106122300 PopulateDocuments: migrating ================================
-- execute("INSERT INTO documents (content_id, locale)\n             SELECT content_id, locale FROM content_items\n             WHERE NOT EXISTS (\n               SELECT 1 FROM documents\n               WHERE documents.content_id = content_items.content_id AND documents.locale = content_items.locale\n             )\n             GROUP BY content_id, locale")
   -> 0.0043s
== 20170106122300 PopulateDocuments: migrated (0.0044s) =======================

== 20170106122400 LinkDocumentsAndEditions: migrating =========================
-- add_column(:content_items, :document_id, :integer)
   -> 0.0004s
-- add_foreign_key(:content_items, :documents)
   -> 0.0018s
== 20170106122400 LinkDocumentsAndEditions: migrated (0.0023s) ================

== 20170106122500 AddDocumentIndexes: migrating ===============================
-- add_index(:content_items, :document_id, {:algorithm=>:concurrently})
   -> 0.0054s
-- add_index(:content_items, [:document_id, :user_facing_version], {:unique=>true, :algorithm=>:concurrently})
   -> 0.0037s
-- add_index(:content_items, [:document_id, :content_store], {:unique=>true, :algorithm=>:concurrently})
   -> 0.0036s
-- add_index(:content_items, [:document_id, :state], {:algorithm=>:concurrently})
   -> 0.0045s
== 20170106122500 AddDocumentIndexes: migrated (0.0174s) ======================

== 20170106122601 DocumentIdNotNull: migrating ================================
-- change_column(:content_items, :document_id, :integer, {:null=>false})
   -> 0.0026s
== 20170106122601 DocumentIdNotNull: migrated (0.0027s) =======================

== 20170106122800 RenameLockVersionColumn: migrating ==========================
-- rename_column(:documents, :lock_version, :stale_lock_version)
   -> 0.0019s
-- rename_column(:link_sets, :lock_version, :stale_lock_version)
   -> 0.0016s
== 20170106122800 RenameLockVersionColumn: migrated (0.0036s) =================

== 20170106122900 ChangeLockVersionDefaults: migrating ========================
-- change_column_default(:link_sets, :stale_lock_version, 0)
   -> 0.0014s
-- change_column_default(:documents, :stale_lock_version, 0)
   -> 0.0012s
== 20170106122900 ChangeLockVersionDefaults: migrated (0.0027s) ===============

== 20170111161439 DeleteDocumentCollectionLinks: migrating ====================
== 20170111161439 DeleteDocumentCollectionLinks: migrated (0.0049s) ===========

== 20170116143200 MoveLockVersionData: migrating ==============================
-- execute("UPDATE link_sets\n             SET stale_lock_version = t.number\n             FROM (SELECT target_id, number FROM lock_versions) t\n             WHERE link_sets.id = t.target_id")
   -> 0.0036s
-- execute("UPDATE documents\n             SET stale_lock_version = COALESCE(t.max_number, 1)\n             FROM (SELECT document_id, MAX(number) AS max_number\n                   FROM content_items LEFT JOIN lock_versions\n                   ON content_items.id = lock_versions.target_id\n                   GROUP BY document_id) t\n             WHERE documents.id = t.document_id")
   -> 0.0037s
== 20170116143200 MoveLockVersionData: migrated (0.0075s) =====================

== 20170123111649 ClearAlphaTaxons: migrating =================================
== 20170123111649 ClearAlphaTaxons: migrated (0.0007s) ========================

== 20170131082645 RemoveDbPillarTables: migrating =============================
-- drop_table(:locations)
   -> 0.0008s
-- drop_table(:states)
   -> 0.0006s
-- drop_table(:translations)
   -> 0.0007s
-- drop_table(:user_facing_versions)
   -> 0.0007s
== 20170131082645 RemoveDbPillarTables: migrated (0.0031s) ====================

== 20170131084254 RemoveLockVersionTable: migrating ===========================
-- drop_table(:lock_versions)
   -> 0.0008s
== 20170131084254 RemoveLockVersionTable: migrated (0.0008s) ==================

== 20170131084734 RenameContentItemsToEditions: migrating =====================
-- rename_table(:content_items, :editions)
   -> 0.0125s
-- rename_column(:access_limits, :content_item_id, :edition_id)
   -> 0.0020s
-- rename_column(:actions, :content_item_id, :edition_id)
   -> 0.0027s
-- rename_column(:change_notes, :content_item_id, :edition_id)
   -> 0.0022s
-- rename_column(:unpublishings, :content_item_id, :edition_id)
   -> 0.0029s
== 20170131084734 RenameContentItemsToEditions: migrated (0.0225s) ============

== 20170131092110 RemoveContentIdAndLocaleFieldsFromEdition: migrating ========
-- remove_column(:editions, :content_id)
   -> 0.0006s
-- remove_column(:editions, :locale)
   -> 0.0002s
== 20170131092110 RemoveContentIdAndLocaleFieldsFromEdition: migrated (0.0009s)

== 20170131143927 AddContentItemFkToLinks: migrating ==========================
-- add_reference(:links, :edition, {:index=>true, :foreign_key=>{:on_delete=>:cascade}})
   -> 0.0129s
== 20170131143927 AddContentItemFkToLinks: migrated (0.0129s) =================

== 20170207155436 ClearAlphaTaxonsAgain: migrating ============================
== 20170207155436 ClearAlphaTaxonsAgain: migrated (0.0015s) ===================

== 20170208172603 AddFactCheckIds: migrating ==================================
-- add_column(:access_limits, :fact_check_ids, :json, {:null=>false, :default=>[]})
   -> 0.0064s
== 20170208172603 AddFactCheckIds: migrated (0.0065s) =========================

== 20170217095802 DeleteProblematicTranslations: migrating ====================
== 20170217095802 DeleteProblematicTranslations: migrated (0.0632s) ===========

== 20170217120853 RemoveInvalidUnpublishings: migrating =======================
== 20170217120853 RemoveInvalidUnpublishings: migrated (0.0079s) ==============

== 20170217134810 AddForeignKeyForUnpublishings: migrating ====================
-- add_foreign_key(:unpublishings, :editions, {:on_delete=>:cascade})
   -> 0.0026s
== 20170217134810 AddForeignKeyForUnpublishings: migrated (0.0026s) ===========

== 20170217140101 AddRedirectsToUnpublishings: migrating ======================
-- add_column(:unpublishings, :redirects, :json)
   -> 0.0004s
== 20170217140101 AddRedirectsToUnpublishings: migrated (0.0004s) =============

== 20170221093606 UpdateOldRedirectUnpublishings: migrating ===================
== 20170221093606 UpdateOldRedirectUnpublishings: migrated (0.0036s) ==========

== 20170223082047 DestroySomeMoreBadWlna: migrating ===========================
== 20170223082047 DestroySomeMoreBadWlna: migrated (0.0037s) ==================

== 20170223160956 IndexDocumentTypeUpdatedAt: migrating =======================
-- add_index(:editions, [:document_type, :updated_at], {:algorithm=>:concurrently})
   -> 0.0048s
-- remove_index(:editions, :document_type)
   -> 0.0074s
== 20170223160956 IndexDocumentTypeUpdatedAt: migrated (0.0123s) ==============

== 20170227130411 ClearSomeContentToAllowWhitehallRepublishing: migrating =====
== 20170227130411 ClearSomeContentToAllowWhitehallRepublishing: migrated (0.0018s)

```

**Comment by mcgoooo** [comment]
good work @kevindew i'll close this one after the slackconvo
